CREATE DATABASE IF NOT EXISTS Login CHARSET utf8mb3 COLLATE utf8mb3_spanish2_ci;
USE Login;

CREATE TABLE IF NOT EXISTS usuarios(
ID INT AUTO_INCREMENT,
USUARIO VARCHAR(30),
CONTRASEÑA BINARY(32),
EMAIL VARCHAR(100),
PRIMARY KEY(ID)
);
